"""Initial Postgres migration

Revision ID: 0c5d1005eac1
Revises: 
Create Date: 2025-02-17 19:59:57.993480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5d1005eac1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('item_uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('jsonld_metadata', sa.JSON(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('item_uuid')
    )
    op.create_index(op.f('ix_item_item_uuid'), 'item', ['item_uuid'], unique=False)
    op.create_index(op.f('ix_item_title'), 'item', ['title'], unique=False)
    op.create_table('relationship',
    sa.Column('relationship_uuid', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('predicate', sa.String(), nullable=True),
    sa.Column('object', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('relationship_uuid')
    )
    op.create_index(op.f('ix_relationship_object'), 'relationship', ['object'], unique=False)
    op.create_index(op.f('ix_relationship_predicate'), 'relationship', ['predicate'], unique=False)
    op.create_index(op.f('ix_relationship_relationship_uuid'), 'relationship', ['relationship_uuid'], unique=False)
    op.create_index(op.f('ix_relationship_subject'), 'relationship', ['subject'], unique=False)
    op.create_table('file',
    sa.Column('file_uuid', sa.String(length=36), nullable=False),
    sa.Column('item_uuid', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('mimetype', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_uuid'], ['item.item_uuid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('file_uuid')
    )
    op.create_index(op.f('ix_file_file_uuid'), 'file', ['file_uuid'], unique=False)
    op.create_index(op.f('ix_file_filename'), 'file', ['filename'], unique=False)
    op.create_index(op.f('ix_file_item_uuid'), 'file', ['item_uuid'], unique=False)
    op.create_index(op.f('ix_file_mimetype'), 'file', ['mimetype'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_mimetype'), table_name='file')
    op.drop_index(op.f('ix_file_item_uuid'), table_name='file')
    op.drop_index(op.f('ix_file_filename'), table_name='file')
    op.drop_index(op.f('ix_file_file_uuid'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_relationship_subject'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_relationship_uuid'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_predicate'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_object'), table_name='relationship')
    op.drop_table('relationship')
    op.drop_index(op.f('ix_item_title'), table_name='item')
    op.drop_index(op.f('ix_item_item_uuid'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
