"""file table drop uri and add item_uuid

Revision ID: 0ba969b30ca6
Revises: 2ed1c354a392
Create Date: 2025-02-07 23:42:27.445785

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ba969b30ca6"
down_revision: Union[str, None] = "2ed1c354a392"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("item_uuid", sa.UUID(), nullable=True))
    op.drop_index("ix_file_storage_uri", table_name="file")
    op.create_index(op.f("ix_file_item_uuid"), "file", ["item_uuid"], unique=False)
    op.drop_column("file", "storage_uri")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("storage_uri", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_file_item_uuid"), table_name="file")
    op.create_index("ix_file_storage_uri", "file", ["storage_uri"], unique=False)
    op.drop_column("file", "item_uuid")
    # ### end Alembic commands ###
