"""create file table

Revision ID: 2ed1c354a392
Revises: c574cbc38101
Create Date: 2025-01-29 10:53:40.846294

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ed1c354a392"
down_revision: Union[str, None] = "c574cbc38101"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file",
        sa.Column("file_uuid", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("mimetype", sa.String(), nullable=True),
        sa.Column("storage_uri", sa.String(), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("date_updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("file_uuid"),
    )
    op.create_index(op.f("ix_file_file_uuid"), "file", ["file_uuid"], unique=False)
    op.create_index(op.f("ix_file_filename"), "file", ["filename"], unique=False)
    op.create_index(op.f("ix_file_mimetype"), "file", ["mimetype"], unique=False)
    op.create_index(op.f("ix_file_storage_uri"), "file", ["storage_uri"], unique=False)
    # ### end Alembic commands ###

    # Create the trigger that calls the function on updates
    op.execute("""
    CREATE TRIGGER update_file_date_updated
    BEFORE UPDATE ON file
    FOR EACH ROW
    EXECUTE FUNCTION update_date_updated_column();
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS update_file_date_updated ON item;")
    op.drop_index(op.f("ix_file_storage_uri"), table_name="file")
    op.drop_index(op.f("ix_file_mimetype"), table_name="file")
    op.drop_index(op.f("ix_file_filename"), table_name="file")
    op.drop_index(op.f("ix_file_file_uuid"), table_name="file")
    op.drop_table("file")
    # ### end Alembic commands ###
