"""foreign key on file to item

Revision ID: 7f14f9b46f7b
Revises: 0ba969b30ca6
Create Date: 2025-02-08 10:16:59.904507

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f14f9b46f7b"
down_revision: Union[str, None] = "0ba969b30ca6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("file", "item_uuid", existing_type=sa.UUID(), nullable=False)
    op.create_foreign_key(
        None, "file", "item", ["item_uuid"], ["item_uuid"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("file", "item_uuid", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
